" Do not use vi-compatible mode
set nocompatible

" Self-explonentary
set encoding=utf-8

" Set $MYVIMRC path to this file -- simulates symlinking on Windows
let $MYVIMRC = "~/dotfiles/.vim/vimrc"

let mapleader="\<Space>"
let maplocalleader=","

" Automatic, language-dependent indentation, syntax coloring and other
" functionality.
filetype indent plugin on
syntax on

" Disable backups -- YOLO
set nowritebackup
set nobackup
set noswapfile
set noundofile

" Set how many command lines to remember
set history=1000

" Reload files when they were changed outside of VIM
set autoread

" Configure VIMs path management
set path+=**
set wildignore+=*\\tmp\\*
set wildignore+=*.swp
set wildignore+=*.zip
set wildignore+=*.exe
set wildignore+=*\\node_modules\\*
set wildignore+=*\\package-lock.json

" Use UNIX line endings
set fileformat=unix
set fileformats=unix

" Windows specific settings
if has('win32')
  let $PYTHONPATH = "C:\\Python36\\Lib;C:\\Python36\\DLLs;C:\\Python36\\Lib\\lib-tk"
endif

" Add current directory to runtimepath
set runtimepath+=~/dotfiles/.vim

" GUI specific settings
if has('gui_running')
  " Turn off scrollbars. (Default on macOS is "egmrL").
  set guioptions=i

  " Temporary workaround for MacVim. It supposedly has +python/dyn and
  " +python3/dyn, but if Python 3 loads first, YCM won't work. Force
  " Python 2 to load first.
  call has('python')

  syntax on
  colorscheme monokai
  set guifont=Fira_Code:h14
  set conceallevel=0

  " Highlight lines exceeding 80 chararecters
  highlight ColorColumn ctermbg=magenta guibg=Magenta
  call matchadd('ColorColumn', '\%81v', 100)
endif

" Specify the behavior when switching between buffers
try
  set switchbuf=useopen,usetab,newtab
  set stal=2
catch
endtry

" Load pathogen
runtime ~/vimfiles/autoload/pathogen.vim
call pathogen#infect()
